// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzSt3_PPHxeDPw_YuYI82DaLrxxUiGyPY',
    appId: '1:84464892226:web:a5d25ff396aec53a74b0db',
    messagingSenderId: '84464892226',
    projectId: 'expensecaluclator',
    authDomain: 'expensecaluclator.firebaseapp.com',
    storageBucket: 'expensecaluclator.firebasestorage.app',
    measurementId: 'G-WY8GHLTKNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPoRaRwgAtTEOEB8Lsdm6K1bc3svJUu-4',
    appId: '1:84464892226:android:e7081c71e774ceb474b0db',
    messagingSenderId: '84464892226',
    projectId: 'expensecaluclator',
    storageBucket: 'expensecaluclator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeUgSNsohjQ9ccEZWnLpaEqM7fgjHXFOg',
    appId: '1:84464892226:ios:afa64a732b8b915774b0db',
    messagingSenderId: '84464892226',
    projectId: 'expensecaluclator',
    storageBucket: 'expensecaluclator.firebasestorage.app',
    iosClientId: '84464892226-9c5nrbn6tcj25u1u39q22584bfvo17rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeUgSNsohjQ9ccEZWnLpaEqM7fgjHXFOg',
    appId: '1:84464892226:ios:afa64a732b8b915774b0db',
    messagingSenderId: '84464892226',
    projectId: 'expensecaluclator',
    storageBucket: 'expensecaluclator.firebasestorage.app',
    iosClientId: '84464892226-9c5nrbn6tcj25u1u39q22584bfvo17rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzSt3_PPHxeDPw_YuYI82DaLrxxUiGyPY',
    appId: '1:84464892226:web:8d86436a6bacc46674b0db',
    messagingSenderId: '84464892226',
    projectId: 'expensecaluclator',
    authDomain: 'expensecaluclator.firebaseapp.com',
    storageBucket: 'expensecaluclator.firebasestorage.app',
    measurementId: 'G-T0VCZ8C82N',
  );

}